name: json_reflectable_example
description: json_reflectable_example
version: 1.0.0

publish_to: none

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  dart_mappable: ^3.1.1
  json_annotation: ^4.8.0
  json_reflectable:
    path: ../

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  build_runner: ^2.3.3
  dart_mappable_builder: ^3.1.1
  json_serializable: ^6.6.1
