name: json_reflectable
description: This package allows programmers to annotate Dart objects for reflective invocation of the fromJson and toJson methods.
version: 1.0.0
homepage: https://github.com/wittyneko/json_reflectable
repository: https://github.com/wittyneko/json_reflectable

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  reflectable: any

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
